name: Rust

on:
  push:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        build:
          - release
          - release-with-cmd

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Rust toolchain
      id: rust-toolchain
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true

    - name: Cache
      uses: actions/cache@v3
      id: cache
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: cache-${{ steps.rust-toolchain.outputs.rustc_hash }}-${{ matrix.build }}-5

    - name: Enable cmd
      run: |
        sed -i '/windows_subsystem = "windows"/d' src/main.rs
        cat src/main.rs
      shell: bash
      if: ${{ matrix.build == 'release-with-cmd' }}

    - name: Build
      run: cargo build --release

    - name: Upload artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.build }}
        path: target/release/wpkg.exe
